### ISSUE TITLE
AnyRTC支持Red5做服务器吗？

### ISSUE THREAD

**Issue by knightjie99** [anyrtcIO-Community/anyRTC-RTMP-OpenSource#101]
我用red5做服务器，部署到linux上。安卓手机端用AnyRTC推流，发现连接上后会隔几秒就 断开了，需要不断的去重连，效果很差。但是我用AnyRTC在PC端推流然后用VLC播放又没问题。所以是AnyRTC的问题，还是Red5不支持移动端？

**Comment by DyncEric** [comment]
应该没问题的。red5之前试过

**Comment by ancin** [comment]
@knightjie99  你好，能否请假你下，server你用的red5吗。你的场景是做直播吗？我的场景想在web端做直播。类似网络教育一样的大课堂。能交流下你们怎么做的吗？
