### ISSUE TITLE
能问下大家 在哪里设置的硬件编码吗

### ISSUE THREAD

**Issue by chenzhu005774** [anyrtcIO-Community/anyRTC-RTMP-OpenSource#123]
能问下大家 在哪里设置的硬件编码吗，我只看到了软件编码
encoder_ = webrtc::H264Encoder::Create();

**Comment by chenzhu005774** [comment]
已经解决了，不过只适配了Android端的所以就不上传代码了

**Comment by Lyon1994** [comment]
@chenzhu005774 你好，具体在那里设置可否方便提示一下呢，我这个也是android端的

**Comment by Lyon1994** [comment]
已找到答案。决定是否使用硬件编码的代码：[`MediaCodecVideoEncoder.java`](https://github.com/anyrtcIO-Community/anyRTC-RTMP-OpenSource/blob/master/Prj-Android/app/src/main/java/org/webrtc/MediaCodecVideoEncoder.java)
```java
    public static boolean isH264HwSupported() {
        return !hwEncoderDisabledTypes.contains(H264_MIME_TYPE) &&
                (findHwEncoder(H264_MIME_TYPE, h264HwList, supportedColorList) != null);
    }
```
#### 例如：增加海思平台的硬件编码支持
[`MediaCodecVideoEncoder.java`](https://github.com/anyrtcIO-Community/anyRTC-RTMP-OpenSource/blob/master/Prj-Android/app/src/main/java/org/webrtc/MediaCodecVideoEncoder.java)
```java

    // List of supported HW H.264 encoders.
    private static final MediaCodecProperties qcomH264HwProperties = new MediaCodecProperties(
            "OMX.qcom.", Build.VERSION_CODES.KITKAT, false /* bitrateAdjustmentRequired */);
    private static final MediaCodecProperties exynosH264HwProperties = new MediaCodecProperties(
            "OMX.Exynos.", Build.VERSION_CODES.LOLLIPOP, true /* bitrateAdjustmentRequired */);
    private static final MediaCodecProperties rkH264HwProperties = new MediaCodecProperties(
            "OMX.rk.", Build.VERSION_CODES.KITKAT, false /* bitrateAdjustmentRequired */);
    /**
     * 增加海思平台的硬件编解码支持
     */
    private static final MediaCodecProperties hisiH264HwProperties = new MediaCodecProperties(
            "OMX.hisi.", Build.VERSION_CODES.KITKAT, false /* bitrateAdjustmentRequired */);
    private static final MediaCodecProperties[] h264HwList = new MediaCodecProperties[]{
            qcomH264HwProperties, exynosH264HwProperties, rkH264HwProperties,hisiH264HwProperties
    };
```
同理，增加硬件解码方案则修改[`MediaCodecVideoDecoder.java`](https://github.com/anyrtcIO-Community/anyRTC-RTMP-OpenSource/blob/master/Prj-Android/app/src/main/java/org/webrtc/MediaCodecVideoDecoder.java)
![image](https://user-images.githubusercontent.com/8456652/96694409-07774080-13bb-11eb-9fde-7f2ab763370a.png)
