### ISSUE TITLE
如何编译windows

### ISSUE THREAD

**Issue by wudelu** [anyrtcIO-Community/anyRTC-RTMP-OpenSource#125]
请问如何编译出windows端

**Comment by DyncEric** [comment]
下载代码后，直接运行vs工程即可

**Comment by wudelu** [comment]
> 下载代码后，直接运行vs工程即可

(h264_decoder_impl.cc:346): avcodec_decode_video2 successful but no frame was decoded. 日志一直输出这个，拉流黑屏
