### ISSUE TITLE
dlopen failed: library "libanyLive.so" not found

### ISSUE THREAD

**Issue by ppjjhh** [anyrtcIO-Community/anyRTC-RTMP-OpenSource#151]
你好，请问为什么使用真机(Redmi note 9 pro - Android 11.0、OPPO Reno - Android 11.0)运行正常，使用android studio模拟器会报以下错误。
```
dlopen failed: library "libanyLive.so" not found
java.lang.NullPointerException: Attempt to invoke virtual method 'io.anyrtc.live.ArLivePusher io.anyrtc.live.ArLiveEngine.createArLivePusher()' on a null object reference
```

Android Studio版本：Android Studio Electric Eel | 2022.1.1 Patch 1
模拟器版本：Pixel 6 API 30，Android 11.0 x86

**Comment by ppjjhh** [comment]
解决了，在build.gradle配置ndk
![Screen Shot 2023-04-17 at 15 36 53](https://user-images.githubusercontent.com/58381529/232417222-88d59253-e66f-4acb-afc9-d24c9a1b09bb.png)

**Comment by ppjjhh** [comment]
在自己的项目的build.gradle

**Comment by chenqinggang001** [comment]
你知道libanyLive.so在哪里下载不
