### ISSUE TITLE
ios的推流一直显示重连～

### ISSUE THREAD

**Issue by yulin6666** [anyrtcIO-Community/anyRTC-RTMP-OpenSource#156]
推流地址用ffmpeg都是可以的，看log也没有啥错误，一直就是重连，是不是哪里还需要设置一下？求大神们帮忙

onPushStatusUpdate status = 1
17:56:37 [💙] onCaptureFirstAudioFrame
17:56:38 [💙] onCaptureFirstVideoFrame
17:56:39 [💙] onPushStatusUpdate status = 3
17:56:40 [💙] onPushStatusUpdate status = 3

定位到是这里总是返回nil，str_format_是“flv“格式，是不是还需要做点啥操作？？？
		AVOutputFormat* output_format = nullptr;
		output_format = av_guess_format(str_format_.c_str(), nullptr, nullptr);
		if (output_format == nullptr)
		{
			Release();
			return false;
		}

**Comment by jhdync** [comment]
ffmpeg 的问题，已更新 @yulin6666

**Comment by yulin6666** [comment]
非常感谢
