### ISSUE TITLE
检测到音频格式是PCM导致没有声音

### ISSUE THREAD

**Issue by MrShuHong** [anyrtcIO-Community/anyRTC-RTMP-OpenSource#160]
我是用这个库推送视频到自己的服务器得到的播放源始终无法播放出声音， 使用了很多第三方的播放器都不行，比如西瓜视频

**Comment by MrShuHong** [comment]
http://v2.h5player.bytedance.com/generate/

**Comment by DyncEric** [comment]
你这边是什么服务器

**Comment by MrShuHong** [comment]
> 你这边是什么服务器

使用的zlmediaKit

**Comment by MrShuHong** [comment]
https://github.com/ZLMediaKit/ZLMediaKit/issues/1214  我看到这里说webrtc 不支持aac 但是我在代码里是看到 我们使用的确实是AAC的编码器 
void ArLive2Pusher::initAudioWithParameters(int nType, int sampleRate, int numChannels, int audBitrate)
{
	webrtc::MutexLock l(&cs_aac_encoder_);
	if (aac_encoder_ == NULL) {
		aac_encoder_ = new webrtc::A_AACEncoder(*this);
		aac_encoder_->Init(sampleRate, numChannels, audBitrate);
	}
}

**Comment by MrShuHong** [comment]
> 你推的是RTMP的流，用webrtc播放。音频需要转码，看下zlmediakit里面有没有配置转码的地方 或者可以试下这个服务，自带转码：https://github.com/X2Rtc/X2Rtc-Stream

我有个地方不理解， 视频用的是h264 音频用的aac编码， 为什么还需要转码呢。 可能我对rtmp和webrtc不太了解。可以在解释的详细一点么

**Comment by DyncEric** [comment]
可以自己查阅相关资料
